export const ErrorMessageConstant = {
  en: {
    CredentialsInvalid: 'Phone number or password is incorrect.',
    EmailCredentialsInvalid: 'Email or password is incorrect.',
    EmailNotExists: 'User with this email does not exist.',
    PasswordIncorrect: 'Wrong password.',
    UserCredentialsExists: 'User with this email already exist.',
    VerificationCodeInvalid: 'Verification Code is invalid',
    AccountAlreadyDeleted: 'Account is already deleted',
    EmailAlreadyExists: 'Email is already registered',
    PhoneNumberAlreadyExists: 'Phone number is already registered',
    UserNotFound: 'User not found',
    CannotResendWithinTime: 'Can not resend the code',
    CodeExpire:
      'Your code has expired. Please wait for some time before requesting a new one',
    EmployeeAccountSuspended: 'Your employee account has been suspended',
    EmployeeRoleSuspended: 'Your role has been suspended',
    MFACodeInvalid: 'MFA Code is Invalid',
    QRCodeNotScanned: 'QR Code is not scanned',
    NotAllowedToSomeRole: 'Not allowed to employee of same role',
    EmployeeAlreadyExists: 'Employee Already Exist with this email',
    EmployeeNotExists: 'Employee not found',
    RoleNotExists: 'Role does not exist for this company',
    NotAllowedToChangeOwner: 'Not allowed to add/update Owner setting ',
    PinAlreadyExists: 'Pin already exists',
    NotAllowedToDeleteAdmin: 'Not Allowed to delete other admin',
    RoleAlreadyExists: 'Role with name already exist in this company',
    QRCodeNotGeneratorError: "Couldn't generate QR code, please try again.",
    NotAllowedToDeleteOwner: 'Not allowed to delete Owner',
    NotAllowedToUpdateAdmin: 'Not Allowed to update other admin',
    NotAllowedToDeleteAdminOrOwnerRole:
      'Not Allowed to delete Admin or Owner Role',
    PermissionNotFound: ` Not found in permissions`,
    NotAllowedToPerformAction: 'Not Allowed to perform this action',
    WarehouseAlreadyExist: 'Warehouse already exists',
    WarehouseNotFound: 'Warehouse not found',
    PosDeviceNotFound: 'POS device not found',
    PosDeviceAlreadyExists: 'POS Device already Exists',
    CategoryAlreadyExists: 'Category already exists',
    CategoryNotFound: 'Category not found',
    StoreAlreadyExists: 'Store with phone number already exists',
    StoreNotFound: 'Store not found',
    InvalidStoreId: 'Invalid store id',
    CustomerAlreadyExists: 'Customer already exists',
    CustomerNotFound: 'Customer not found',
    InvalidCategoryId: 'Invalid Category Id',
    SupplierPhoneNumberAlreadyExists: 'Supplier phone number already exists',
    SupplierEmailAlreadyExists: 'Supplier email already exists',
    SupplierNotFound: 'Supplier not found',
    ItemAlreadyExists: 'Item Already exists',
    ItemNotFound: 'Item not found',
    SkuAlreadyExist: 'Duplicate SKU found in variants: ',
    ItemImageRequired: 'Item image required',
    ItemStoreNotFound: 'Item store does not find',
    AssociateItemNotExists: 'Associated Item does not exist',
    ItemExistInComposite: 'Item already exist in composite',
    ExpenseNotFound: 'Expense not found',
    PurchaseOrderNotFound: 'Purchase Order Not Found',
    ExpectedDeliveryDateLessThanToday:
      'Expected delivery date must not be less than today',
    DestinationStoreNotFound: 'Destination Store not found',
    SourceStoreNotFound: 'Source Store not found',
    TransferDateMustBeGreater: 'Transfer Date must be greater',
    SourceAndDestinationStoresMustBeDifferent:
      'Source And Destination Store must be different',
    TransferOrderNotFound: 'Transfer Order not found',
    StockAdjustmentNotFound: 'Stock Adjustment not found',
    PaymentTypeAlreadyExist: 'Payment Type Already Exist',
    PaymentTypeNotFound: 'Payment Type Not Found',
    DeviceAlreadyBound: 'Device already bound',
    DeviceNotBindToStore:
      'Device or Employee may be not connected to the store',
    IncorrectPin: 'Incorrect Employee Pin',
    CategoryInActive: 'Category is inactive',
    ItemImageIsNotProvided: 'Item Image is not provided',
    ItemUnavailable: 'Item Unavailable',
    DiscountNotAllowed: 'Discount not allowed',
    DiscountExceedsLimit: 'Discount exceeds the limit',
    CartNotFound: 'Cart not found',
    AmountExceedsPayable: 'Payed amount exceeds the payable amount',
    OrderNotFound: 'Order not found',
    OrderShouldBePending: 'Only pending orders can be fulfilled',
    InactiveCompany: 'Company is not active, make your your company email is phone number is verified',
    TransferOrderStatusMustBeApproved: 'Transfer Order must be approved',
    TransferOrderStatusMustBeInShipmentOrApproved: 'Transfer Order must be in shipment or approved',
    TransferOrderStatusMustBePendingApproval: 'Transfer Order must be in pending approval',
    MinimumServicePriceError: 'Service price must not be less than minimum service price',
    MinimumItemPriceError: 'Item price must not be less than the sale price',
    OrderAlreadyPaid: 'Order is already paid',
    TokenInvalid: 'Reset password token is invalid or expired',
    TransferOrderNotBelongToStore: 'Transfer Order does not belong to store',
    SourceStoreException: 'In Shipment status can only be mark by Source Store',
    DestinationSourceException: 'Complete Status can only be mark by Destination Store',
    EmployeeNotExistInStore: 'Employee does not exist in store',
    CashierDeviceNotFound: 'Cashier Device not found',
    ShiftAlreadyExist: 'Shift already started on this POS Device',
    ShiftNotFound: 'Shift Not Found',
    PaymentMethodNotActive: 'Payment Method is inactive',
    PaymentMethodNotFound: 'Payment method not found ',
    FulfillOrderCannotBeCancelled: 'Fulfill order cannot be cancelled',
    PaymentAmountExceedsRemainingBalance: 'Payment amount exceeds remaining balance',
    ShiftFeatureNotEnabled: 'Shift feature is not enabled',
    OrderAlreadyFulfilled: 'Order already fulfilled',
    ServiceTypeNotFound: 'Service type not found',
    CompanySettingNotFound: 'Company setting not found',
    SerialNumberExist: 'Serial number already exists',
    SerialNumberQuantityMismatch: 'Serial number quantity mismatch',
    AdminAccountSuspended: 'Your admin account has been suspended',
  },
  /* cSpell:disable */
  ar: {
    CredentialsInvalid: '[Ar] Phone number or password is incorrect.',
    EmailCredentialsInvalid: '[Ar] Email or password is incorrect.',
    EmailNotExists: '[Ar] User with this email does not exist.',
    PasswordIncorrect: '[Ar] Wrong password.',
    UserCredentialsExists: '[Ar] User with this email already exist.',
    VerificationCodeInvalid: '[Ar] Verification Code is invalid',
    AccountAlreadyDeleted: '[Ar] Account is already deleted',
    EmailAlreadyExists: '[Ar] Email is already registered',
    PhoneNumberAlreadyExists: '[Ar] Phone number is already registered',
    UserNotFound: '[Ar] User not found',
    CannotResendWithinTime: '[Ar] Can not resend the code',
    CodeExpire: '[Ar] Your code has expired. Please wait for some time before requesting a new one',
    EmployeeAccountSuspended: '[Ar] Your employee account has been suspended',
    EmployeeRoleSuspended: '[Ar] Your role has been suspended',
    MFACodeInvalid: '[Ar] MFA Code is Invalid',
    QRCodeNotScanned: '[Ar] QR Code is not scanned',
    NotAllowedToSomeRole: '[Ar] Not allowed to employee of same role',
    EmployeeAlreadyExists: '[Ar] Employee Already Exist with this email',
    EmployeeNotExists: '[Ar] Employee not found',
    RoleNotExists: '[Ar] Role does not exist for this company',
    NotAllowedToChangeOwner: '[Ar] Not allowed to add/update Owner setting',
    PinAlreadyExists: '[Ar] Pin already exists',
    NotAllowedToDeleteAdmin: '[Ar] Not Allowed to delete other admin',
    RoleAlreadyExists: '[Ar] Role with name already exist in this company',
    QRCodeNotGeneratorError: '[Ar] Couldn\'t generate QR code, please try again.',
    NotAllowedToDeleteOwner: '[Ar] Not allowed to delete Owner',
    NotAllowedToUpdateAdmin: '[Ar] Not Allowed to update other admin',
    NotAllowedToDeleteAdminOrOwnerRole: '[Ar] Not Allowed to delete Admin or Owner Role',
    PermissionNotFound: '[Ar] Not found in permissions',
    NotAllowedToPerformAction: '[Ar] Not Allowed to perform this action',
    WarehouseAlreadyExist: '[Ar] Warehouse already exists',
    WarehouseNotFound: '[Ar] Warehouse not found',
    PosDeviceNotFound: '[Ar] POS device not found',
    PosDeviceAlreadyExists: '[Ar] POS Device already Exists',
    CategoryAlreadyExists: '[Ar] Category already exists',
    CategoryNotFound: '[Ar] Category not found',
    StoreAlreadyExists: '[Ar] Store with phone number already exists',
    StoreNotFound: '[Ar] Store not found',
    InvalidStoreId: '[Ar] Invalid store id',
    CustomerAlreadyExists: '[Ar] Customer already exists',
    CustomerNotFound: '[Ar] Customer not found',
    InvalidCategoryId: '[Ar] Invalid Category Id',
    SupplierPhoneNumberAlreadyExists: '[Ar] Supplier phone number already exists',
    SupplierEmailAlreadyExists: '[Ar] Supplier email already exists',
    SupplierNotFound: '[Ar] Supplier not found',
    ItemAlreadyExists: '[Ar] Item Already exists',
    ItemNotFound: '[Ar] Item not found',
    SkuAlreadyExist: '[Ar] Duplicate SKU found in variants:',
    ItemImageRequired: '[Ar] Item image required',
    ItemStoreNotFound: '[Ar] Item store does not find',
    AssociateItemNotExists: '[Ar] Associated Item does not exist',
    ItemExistInComposite: '[Ar] Item already exist in composite',
    ExpenseNotFound: '[Ar] Expense not found',
    PurchaseOrderNotFound: '[Ar] Purchase Order Not Found',
    ExpectedDeliveryDateLessThanToday: '[Ar] Expected delivery date must not be less than today',
    DestinationStoreNotFound: '[Ar] Destination Store not found',
    SourceStoreNotFound: '[Ar] Source Store not found',
    TransferDateMustBeGreater: '[Ar] Transfer Date must be greater',
    SourceAndDestinationStoresMustBeDifferent: '[Ar] Source And Destination Store must be different',
    TransferOrderNotFound: '[Ar] Transfer Order not found',
    StockAdjustmentNotFound: '[Ar] Stock Adjustment not found',
    PaymentTypeAlreadyExist: '[Ar] Payment Type Already Exist',
    PaymentTypeNotFound: '[Ar] Payment Type Not Found',
    DeviceAlreadyBound: '[Ar] Device already bound',
    DeviceNotBindToStore: '[Ar] Device or Employee may be not connected to the store',
    IncorrectPin: '[Ar] Incorrect Employee Pin',
    CategoryInActive: '[Ar] Category is inactive',
    ItemImageIsNotProvided: '[Ar] Item Image is not provided',
    ItemUnavailable: '[Ar] Item Unavailable',
    DiscountNotAllowed: '[Ar] Discount not allowed',
    DiscountExceedsLimit: '[Ar] Discount exceeds the limit',
    CartNotFound: '[Ar] Cart not found',
    AmountExceedsPayable: '[Ar] Payed amount exceeds the payable amount',
    OrderNotFound: '[Ar] Order not found',
    OrderShouldBePending: '[Ar] Only pending orders can be fulfilled',
    InactiveCompany: '[Ar] Company is not active, make your company email and phone number verified',
    TransferOrderStatusMustBeApproved: '[Ar] Transfer Order must be approved',
    TransferOrderStatusMustBeInShipmentOrApproved: '[Ar] Transfer Order must be in shipment or approved',
    TransferOrderStatusMustBePendingApproval: '[Ar] Transfer Order must be in pending approval',
    MinimumServicePriceError: '[Ar] Service price must not be less than minimum service price',
    MinimumItemPriceError: '[Ar] Item price must not be less than the sale price',
    OrderAlreadyPaid: '[Ar] Order is already paid',
    TokenInvalid: '[Ar] Reset password token is invalid or expired',
    TransferOrderNotBelongToStore: '[Ar] Transfer Order does not belong to store',
    SourceStoreException: '[Ar] In Shipment status can only be mark by Source Store',
    DestinationSourceException: '[Ar] Complete Status can only be mark by Destination Store',
    EmployeeNotExistInStore: '[Ar] Employee does not exist in store',
    CashierDeviceNotFound: '[Ar] Cashier Device not found',
    ShiftAlreadyExist: '[Ar] Shift already started on this POS Device',
    ShiftNotFound: '[Ar] Shift Not Found',
    PaymentMethodNotActive: '[Ar] Payment Method is inactive',
    PaymentMethodNotFound: '[Ar] Payment method not found',
    FulfillOrderCannotBeCancelled: '[Ar] Fulfill order cannot be cancelled',
    PaymentAmountExceedsRemainingBalance: '[Ar] Payment amount exceeds remaining balance',
    ShiftFeatureNotEnabled: '[Ar] Shift feature is not enabled',
    OrderAlreadyFulfilled: '[Ar] Order already fulfilled',
    ServiceTypeNotFound: '[Ar] Service type not found',
    CompanySettingNotFound: '[Ar] Company setting not found',
    SerialNumberExist: '[Ar] Serial number already exists',
    SerialNumberQuantityMismatch: '[Ar] Serial number quantity mismatch',
    AdminAccountSuspended: '[AR] Your admin account has been suspended',
  },
};
